# Generated by Django 4.2.2 on 2023-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Fecha', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=60)),
                ('Image', models.CharField(max_length=500)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Lugar', models.CharField(max_length=50)),
                ('Cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEvento', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=60)),
                ('secciones', models.CharField(max_length=60)),
            ],
        ),
    ]
